import { type Session } from 'next-auth'
import { SessionProvider } from 'next-auth/react'
import { type AppType } from 'next/app'

import { api } from '@/utils/api'

import '@/styles/globals.css'
import { ThemeProvider } from 'next-themes'
// import { useEffect, useState } from 'react'
import Layout from '@/components/layout/Layout'
import { THEME } from '@/hooks/useToggleTheme'
import Head from 'next/head'

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  // const [mounted, setMounted] = useState(false)

  // useEffect(() => {
  //   setMounted(true)
  // }, [])

  // if (!mounted) return null
  return (
    <>
      <Head>
        <title>Spotify v1</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ThemeProvider
        attribute='data-theme'
        defaultTheme={THEME.DARK}
        themes={[THEME.DARK, THEME.LIGHT]}
      >
        <SessionProvider session={session}>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </SessionProvider>
      </ThemeProvider>
    </>
  )
}

export default api.withTRPC(MyApp)
