import { type GetServerSideProps, type NextPage } from 'next'
import Head from 'next/head'

import { getServerAuthSession } from '@/server/auth'
import Sidebar from '@/components/Sidebar'
import Center from '@/components/Center'
import CurrentTrack from '@/components/CurrentTrack'

type Props = {
  session: Awaited<ReturnType<typeof getServerAuthSession>>
}

export const getServerSideProps: GetServerSideProps<Props> = async ctx => {
  const session = await getServerAuthSession(ctx)
  if (!session) {
    return {
      redirect: {
        destination: '/login',
        permanent: true,
      },
    }
  }
  return {
    props: {
      session,
    },
  }
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Spotify v1</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='relative flex h-screen bg-base-100'>
        <Sidebar />
        <Center />
        <CurrentTrack />
      </main>
    </>
  )
}

export default Home
